### ISSUE TITLE
Informations contenues dans le SMS

### ISSUE THREAD

**Issue by hugokernel** [YannickF/Rika-REVO-GSM-modem-emulator#1]
Bonjour Yannick,

Merci pour le partage du projet.

J'ai un poêle Rika Como que je souhaite domotiser d'une façon un peu plus intelligente qu'en passant par l'envoi de SMS et d'une manière plus direct que Firenet: Ton approche semble donc être la même que la mienne.

J'ai un souci de lecture des commandes AT sur le port série du poêle, je reçois `_` (0x5F), `U` (0x55) et `CR` (0x0D) qui se répète 3 fois avec un intervalle d'environ 4 secondes avant que l’initialisation ne s'arrête (j'ai tenté avec plusieurs adaptateurs série 3V et directement sur le port série du Raspberry).
Cependant, en faisant la mesure et le décodage avec mon oscilloscope, je lis bien l'information voulue (`A`, `T`, `CR`), en fait, il semblerait qu'il y est un bit de start, ce qui expliquerait pourquoi j'ai des lectures erronées (voir capture d'écran).

Dans la mesure ou je souhaiterai obtenir un maximum d'information (consigne, status, quantité de pellets consommés, etc...) concernant le poêle et que la piste via le port série n'est peut être pas la bonne, pourrais-tu m'indiquer quel est le contenu du SMS envoyé par le poêle ?

Merci pour les informations.

![DS2_2022121917138](https://user-images.githubusercontent.com/167398/208624066-2015a28a-0c20-4af2-a34e-85b6e01e37eb.png)

**Comment by YannickF** [comment]
Salut

Ca fait des années que je n’ai pas mis le nez là-dedans.

Je me souviens juste que le poêle envoie régulièrement des commandes et qu’il attend une réponse « OK » +CR +LF

Sans ça, il considère que le modem GSM est absent

**Comment by hugokernel** [comment]
Le sujet du ticket concerne essentiellement le contenu du SMS, pour le problème de communication, je vais me débrouiller.

As-tu le contenu complet d'un SMS ? Ou au pire de mémoire m'indiquer ce qu'ils contiennent ?

Merci.

**Comment by YannickF** [comment]
Le contenu d’un SMS est ultrasimple 

1234 heat
1234 room
1234 off
1234 auto
1234 h55
1234 r22

Où 1234 est le code à 4 chiffres défini sur le poêle

Et le reste correspond au mode qu’on veut

Si on met juste h (pour heat) ou r (pour room) il faut donner un nombre pour la puissante (mode h) ou la température (mode room)

Ensuite le poêle répond en envoyant un SMS avec en clair le mode dans lequel il vient de basculer
Sur ma version de firmware (un peu ancienne) ce sont les seules possibilités, il y a ensuite eu des versions plus récente où on pouvait demander le Status du poêle par SMS


Tout est dans le code dispo sur GitHub

**Comment by YannickF** [comment]
> Le 20 déc. 2022 à 17:15, Charles R. ***@***.***> a écrit :
> 
> 
> Le sujet du ticket concerne essentiellement le contenu du SMS, pour le problème de communication, je vais me débrouiller.
> 
> As-tu le contenu complet d'un SMS ? Ou au pire de mémoire m'indiquer ce qu'ils contiennent ?
> 
> Merci.
> 


En cas d’erreur le SMS en réponse du poêle est : 
FAILURE : NO PELLETS
FAILURE : NOT IGNITED
FAILURE : FAN ERROR

Il y a des PDF avec tous les messages sur le site de Rika, pour le modem GSM (à trouver en archives)

**Comment by hugokernel** [comment]
Ok, merci pour le retour.

Je vais faire quelques tests en espérant réussir à communiquer avec l'engin ;)
